--
-- PostgreSQL database dump
--

-- Dumped from database version 15.0
-- Dumped by pg_dump version 15.0

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: actions; Type: TABLE; Schema: public; Owner: andrejdavidcenko
--

CREATE TABLE public.actions (
    id_film text,
    id_actor text
);


ALTER TABLE public.actions OWNER TO andrejdavidcenko;

--
-- Name: actors; Type: TABLE; Schema: public; Owner: andrejdavidcenko
--

CREATE TABLE public.actors (
    id text NOT NULL,
    name text,
    b_date date
);


ALTER TABLE public.actors OWNER TO andrejdavidcenko;

--
-- Name: directors; Type: TABLE; Schema: public; Owner: andrejdavidcenko
--

CREATE TABLE public.directors (
    id text NOT NULL,
    name text,
    b_date date
);


ALTER TABLE public.directors OWNER TO andrejdavidcenko;

--
-- Name: films; Type: TABLE; Schema: public; Owner: andrejdavidcenko
--

CREATE TABLE public.films (
    id_imdb text NOT NULL,
    title text,
    year integer,
    imdb_rating numeric(3,1)
);


ALTER TABLE public.films OWNER TO andrejdavidcenko;

--
-- Name: films_directors; Type: TABLE; Schema: public; Owner: andrejdavidcenko
--

CREATE TABLE public.films_directors (
    id_imdb text,
    id_director text
);


ALTER TABLE public.films_directors OWNER TO andrejdavidcenko;

--
-- Name: films_genre; Type: TABLE; Schema: public; Owner: andrejdavidcenko
--

CREATE TABLE public.films_genre (
    id_imdb text,
    id_genre integer
);


ALTER TABLE public.films_genre OWNER TO andrejdavidcenko;

--
-- Name: genre; Type: TABLE; Schema: public; Owner: andrejdavidcenko
--

CREATE TABLE public.genre (
    id integer NOT NULL,
    name text
);


ALTER TABLE public.genre OWNER TO andrejdavidcenko;

--
-- Name: genre_id_seq; Type: SEQUENCE; Schema: public; Owner: andrejdavidcenko
--

ALTER TABLE public.genre ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.genre_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: type_role; Type: TABLE; Schema: public; Owner: andrejdavidcenko
--

CREATE TABLE public.type_role (
    id integer NOT NULL,
    shot_name text
);


ALTER TABLE public.type_role OWNER TO andrejdavidcenko;

--
-- Name: type_role_id_seq; Type: SEQUENCE; Schema: public; Owner: andrejdavidcenko
--

ALTER TABLE public.type_role ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.type_role_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: actions; Type: TABLE DATA; Schema: public; Owner: andrejdavidcenko
--

COPY public.actions (id_film, id_actor) FROM stdin;
\.


--
-- Data for Name: actors; Type: TABLE DATA; Schema: public; Owner: andrejdavidcenko
--

COPY public.actors (id, name, b_date) FROM stdin;
\.


--
-- Data for Name: directors; Type: TABLE DATA; Schema: public; Owner: andrejdavidcenko
--

COPY public.directors (id, name, b_date) FROM stdin;
\.


--
-- Data for Name: films; Type: TABLE DATA; Schema: public; Owner: andrejdavidcenko
--

COPY public.films (id_imdb, title, year, imdb_rating) FROM stdin;
\.


--
-- Data for Name: films_directors; Type: TABLE DATA; Schema: public; Owner: andrejdavidcenko
--

COPY public.films_directors (id_imdb, id_director) FROM stdin;
\.


--
-- Data for Name: films_genre; Type: TABLE DATA; Schema: public; Owner: andrejdavidcenko
--

COPY public.films_genre (id_imdb, id_genre) FROM stdin;
\.


--
-- Data for Name: genre; Type: TABLE DATA; Schema: public; Owner: andrejdavidcenko
--

COPY public.genre (id, name) FROM stdin;
2	Action
3	Crime
4	Thriller
\.


--
-- Data for Name: type_role; Type: TABLE DATA; Schema: public; Owner: andrejdavidcenko
--

COPY public.type_role (id, shot_name) FROM stdin;
1	primery
2	secondary
\.


--
-- Name: genre_id_seq; Type: SEQUENCE SET; Schema: public; Owner: andrejdavidcenko
--

SELECT pg_catalog.setval('public.genre_id_seq', 4, true);


--
-- Name: type_role_id_seq; Type: SEQUENCE SET; Schema: public; Owner: andrejdavidcenko
--

SELECT pg_catalog.setval('public.type_role_id_seq', 2, true);


--
-- Name: actions actions_id_film_id_actor_key; Type: CONSTRAINT; Schema: public; Owner: andrejdavidcenko
--

ALTER TABLE ONLY public.actions
    ADD CONSTRAINT actions_id_film_id_actor_key UNIQUE (id_film, id_actor);


--
-- Name: actors actors_name_b_date_key; Type: CONSTRAINT; Schema: public; Owner: andrejdavidcenko
--

ALTER TABLE ONLY public.actors
    ADD CONSTRAINT actors_name_b_date_key UNIQUE (name, b_date);


--
-- Name: actors actors_pkey; Type: CONSTRAINT; Schema: public; Owner: andrejdavidcenko
--

ALTER TABLE ONLY public.actors
    ADD CONSTRAINT actors_pkey PRIMARY KEY (id);


--
-- Name: directors directors_name_b_date_key; Type: CONSTRAINT; Schema: public; Owner: andrejdavidcenko
--

ALTER TABLE ONLY public.directors
    ADD CONSTRAINT directors_name_b_date_key UNIQUE (name, b_date);


--
-- Name: directors directors_pkey; Type: CONSTRAINT; Schema: public; Owner: andrejdavidcenko
--

ALTER TABLE ONLY public.directors
    ADD CONSTRAINT directors_pkey PRIMARY KEY (id);


--
-- Name: films_directors films_directors_id_imdb_id_director_key; Type: CONSTRAINT; Schema: public; Owner: andrejdavidcenko
--

ALTER TABLE ONLY public.films_directors
    ADD CONSTRAINT films_directors_id_imdb_id_director_key UNIQUE (id_imdb, id_director);


--
-- Name: films_genre films_genre_id_imdb_id_genre_key; Type: CONSTRAINT; Schema: public; Owner: andrejdavidcenko
--

ALTER TABLE ONLY public.films_genre
    ADD CONSTRAINT films_genre_id_imdb_id_genre_key UNIQUE (id_imdb, id_genre);


--
-- Name: films films_pkey; Type: CONSTRAINT; Schema: public; Owner: andrejdavidcenko
--

ALTER TABLE ONLY public.films
    ADD CONSTRAINT films_pkey PRIMARY KEY (id_imdb);


--
-- Name: films films_title_year_key; Type: CONSTRAINT; Schema: public; Owner: andrejdavidcenko
--

ALTER TABLE ONLY public.films
    ADD CONSTRAINT films_title_year_key UNIQUE (title, year);


--
-- Name: genre genre_name_key; Type: CONSTRAINT; Schema: public; Owner: andrejdavidcenko
--

ALTER TABLE ONLY public.genre
    ADD CONSTRAINT genre_name_key UNIQUE (name);


--
-- Name: genre genre_pkey; Type: CONSTRAINT; Schema: public; Owner: andrejdavidcenko
--

ALTER TABLE ONLY public.genre
    ADD CONSTRAINT genre_pkey PRIMARY KEY (id);


--
-- Name: type_role type_role_pkey; Type: CONSTRAINT; Schema: public; Owner: andrejdavidcenko
--

ALTER TABLE ONLY public.type_role
    ADD CONSTRAINT type_role_pkey PRIMARY KEY (id);


--
-- Name: type_role type_role_shot_name_key; Type: CONSTRAINT; Schema: public; Owner: andrejdavidcenko
--

ALTER TABLE ONLY public.type_role
    ADD CONSTRAINT type_role_shot_name_key UNIQUE (shot_name);


--
-- Name: actions actions_id_actor_fkey; Type: FK CONSTRAINT; Schema: public; Owner: andrejdavidcenko
--

ALTER TABLE ONLY public.actions
    ADD CONSTRAINT actions_id_actor_fkey FOREIGN KEY (id_actor) REFERENCES public.actors(id);


--
-- Name: actions actions_id_film_fkey; Type: FK CONSTRAINT; Schema: public; Owner: andrejdavidcenko
--

ALTER TABLE ONLY public.actions
    ADD CONSTRAINT actions_id_film_fkey FOREIGN KEY (id_film) REFERENCES public.films(id_imdb);


--
-- Name: films_directors films_directors_id_director_fkey; Type: FK CONSTRAINT; Schema: public; Owner: andrejdavidcenko
--

ALTER TABLE ONLY public.films_directors
    ADD CONSTRAINT films_directors_id_director_fkey FOREIGN KEY (id_director) REFERENCES public.directors(id);


--
-- Name: films_directors films_directors_id_imdb_fkey; Type: FK CONSTRAINT; Schema: public; Owner: andrejdavidcenko
--

ALTER TABLE ONLY public.films_directors
    ADD CONSTRAINT films_directors_id_imdb_fkey FOREIGN KEY (id_imdb) REFERENCES public.films(id_imdb);


--
-- Name: films_genre films_genre_id_genre_fkey; Type: FK CONSTRAINT; Schema: public; Owner: andrejdavidcenko
--

ALTER TABLE ONLY public.films_genre
    ADD CONSTRAINT films_genre_id_genre_fkey FOREIGN KEY (id_genre) REFERENCES public.genre(id);


--
-- Name: films_genre films_genre_id_imdb_fkey; Type: FK CONSTRAINT; Schema: public; Owner: andrejdavidcenko
--

ALTER TABLE ONLY public.films_genre
    ADD CONSTRAINT films_genre_id_imdb_fkey FOREIGN KEY (id_imdb) REFERENCES public.films(id_imdb);


--
-- PostgreSQL database dump complete
--

